### ISSUE TITLE
how to use or understand the script

### ISSUE THREAD

**Issue by SUN123RAY** [QijingZheng/VASP_XDATCAR#1]
hi 
Thanks Zheng, for writing such a nice script. 
since there is no "manual", its hard for me to understand how to execute the script? 
I have just copied and execute your script, it gave a plot, I guess that is total RDF ( radial distribution function). But how to get individual pair contribution ? Moreover how to plot VACF and DOS ? 

Can you please explain me, how to use your script wisely?

**Comment by QijingZheng** [comment]
Hi 

- Check the last few lines of the script for examples.
  ``` python
  # read the XDATCAR
  inp = xdatcar('path/to/your/XDATCAR')
  # get the velocity autocorrelation function, which will be used to 
  # get the phonon DOS 
  inp.getVAF()
  # get the phonon DOS if you want, the unit of the frequency is 'cm-1'
  omega, dos = inp.phononDOS(unit='cm-1')
  # get the pair correlation function of element A='H' and element B='O' 
  # ( Is this what you called radial distribution function?)
  val, bins = inp.PCF(bins=100, A='H', B='O')

  # then if you don't know matplotlib, you can just save the data and use 
  # whatever plotting software you like to get the resulting figure.
  np.savetxt('pdos.dat', np.array([omega, dos]).T)
  np.savetxt('pcf.dat', np.array([val, bins]).T)

  # if you know matplotlib, it is easier...
  import matplotlib.pyplot as plt
  plt.plot(omega, pdos)
  # or
  plt.plot(val, bins)
  ```

**Comment by SUN123RAY** [comment]
thanks Zheng.
I have inserted your correction. Then I got this error :
Traceback (most recent call last):
  File "xdatcar.py", line 257, in <module>
    omega, dos = inp.phononDOS(unit='cm-1')
AttributeError: xdatcar instance has no attribute 'phononDOS'

which is because of different assignment, like on the script class is name
as 'phononDos'. So that I have fixed.  But again it shows this error

"Traceback (most recent call last):
  File "xdatcar.py", line 259, in <module>
    val, bins = inp.PCF(bins=100, A='H', B='O')
  File "xdatcar.py", line 234, in PCF
    rABs = np.linalg.norm(np.dot(self.cell, rABs.T), axis=0)
ValueError: shapes (3,3) and (0,) not aligned: 3 (dim 1) != 0 (dim 0)
"

**Comment by SUN123RAY** [comment]
val, bins = inp.PCF(bins=100, A='H', B='O')
is it because i dont have H and O in my XDATCAR?

**Comment by SUN123RAY** [comment]
Zheng,

after changing A and B in inp.PCF.
I got this error message, not able to write pdf.dat

Traceback (most recent call last):
  File "xdatcar.py", line 263, in <module>
    np.savetxt('pcf.dat', np.array([val, bin]).T)
  File
"/software/apps/python/2.7.12/anaconda-4.1.1/lib/python2.7/site-packages/numpy/lib/npyio.py",
line 1162, in savetxt
    % (str(X.dtype), format))
TypeError: Mismatch between array dtype ('object') and format specifier
('%.18e')

**Comment by QijingZheng** [comment]
Hi 

There is a typo in your np.savetxt line, change "bin" to "bins"

Best
